### ISSUE TITLE
Set a relationship from a different namespace as default

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#227]
In GitLab by @yoavnash on Jan 7, 2020, 16:28

Currently it's only possible to set a relationship from the same namespace as the default one.

**Comment by aaronAB1993** [comment]
@yoavnash you can now refer to a relationship from a different namespace:

```yml
---
    version: "0.0.3"
    
    namespace: "default_rel_test_namespace_two_definitions"
    default_rel: cuba.activeRelationship
    ontology:
      SomeEntity:
        subclass_of:
          - cuba.Entity
      someRel:
        subclass_of:
          - cuba.activeRelationship
```

The "old" way to mark a default relationship is still valid:
```yml
---
    version: "0.0.3"
    
    namespace: "default_rel_test_namespace_two_definitions"
    ontology:
      SomeEntity:
        subclass_of:
          - cuba.Entity
      someRel:
        subclass_of:
          - cuba.activeRelationship
        default_rel: true
```
also works. However, when you do both, it raises an error, because defining the default twice doesn't make any sense.
