### ISSUE TITLE
Support complex class expressions.

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#443]
Both owl and yaml can contain complex class expressions. Currently they cannot be accessed by osp-core >= v3.9

**Comment by urbanmatthias** [comment]
In both OWL and YAML, entities can not only be subclasses, but also [Class Expressions](https://www.w3.org/TR/owl2-syntax/#Class_Expressions), like e.g. [Object Property Restrictions](https://www.w3.org/TR/owl2-syntax/#Object_Property_Restrictions).

Classes are basically sets of individuals (aka CUDS objects). In its definition you can say which individuals are part of it. E.g. if you say that a city is a subclass of a populated place, you're basically saying, that the set city is a subset of the set populated place. The difference between class expressions and Classes is that former don't have a name.

Example im YAML code:
```
  PopulatedPlace:
    subclass_of:
    - city.GeographicalPlace
    - city.hasInhabitant:
        range: city.Citizen
        cardinality: some
        exclusive: true
```

The class PopulatedPlace is a subclass of the class GeographicalPlace. That means all populated places (individuals aka CUDS objects) are also geographical places. The set of all populated places is a subset of the set of all geographical places. Furthermore, the set of all populated places is a subset of the set of all individuals that are only connected to to citizens via the hasInhabitant relation (exclusive=True) and at least one citizen must be connected (cardinality: some).

You see that
```
city.hasInhabitant:
        range: city.Citizen
        cardinality: some
        exclusive: true
```
defines a set of individuals, but it doesn't have a name. This is why it's a class expression rather than a class.

In owl you use ObjectAllValuesFrom (for exclusive=True) and ObjectSomeValuesFrom (for cardinality=some).
Note that class expressions can also be nested. I.e. the range (here Citizen) could also be another class expression.

This information is mainly used by the reasoner, which uses this information to generate new knowledge. If some individual is connected via hasInhabitant to a populated place, the reasoner infers, that this individual must be a Citizen.

In this issue we want to make it possible for the user to query these class expressions from code, [as it was possible in version <= 3.8 of osp-core](https://github.com/simphony/osp-core/blob/01759b4388031400712d6e737039bb2909fe14a0/osp/core/ontology/oclass.py#L53). In the last update I dropped that.

In this issues you would need to get more familiar with owl, and how it is serialized in RDF (because we load the ontology in an rdf triplestore).

I think this could be a larger issue which is not really urgent.
