### ISSUE TITLE
Installable dependencies of dcat

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#539]
Create YAML files that lets the user install the dependencies of dcat.

**Comment by urbanmatthias** [comment]
Currently the YAML file for DCAT looks like this:

```yml
---
identifier: dcat2
ontology_file: https://www.w3.org/ns/dcat2.rdf
reference_by_label: False
namespaces: 
    dcat2: http://www.w3.org/ns/dcat#
active_relationships: [] 
```

Looking at the DCAT specifications, there are a couple of dependencies that are currently not installed on `pico install dcat2`.

![image](https://user-images.githubusercontent.com/42069939/111428520-e7dd0d80-86f7-11eb-8eb2-3c958f2462e3.png)

It would be nice if these ontologies would be loaded automatically, without the need of specifying another YAML.
