### ISSUE TITLE
Infer ontology format from file extension

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#557]
```yml
identifier: software
ontology_file: .\software-ontology.ttl
reference_by_label: True
namespaces:
    software: http://www.semanticweb.org/yoav/ontologies/2021/0/software-ontology
format: turtle
```

format.ttl should not be necessary due to file extension ttl
