### ISSUE TITLE
Change of attributes for added individuals

### ISSUE THREAD

**Issue by paulzierep** [simphony/osp-core#679]
In the example: 

```
import os
from osp.core.namespaces import city
from osp.core.utils import pretty_print

freiburg = city.City(name="Freiburg")
industrial_area = city.Neighborhood(name = 'Industrie Gebiet')

freiburg.add(industrial_area)

pretty_print(freiburg)

freiburg.coordinates[0] = 1

pretty_print(freiburg)
```

Output:
```
- Cuds object named <Freiburg>:
  uid: 189eebe0-ead3-4d4d-a738-d25d13b976d5
  type: city.City
  superclasses: city.City, city.GeographicalPlace, city.PopulatedPlace, cuba.Entity
  values: coordinates: [0 0]
  description: 
    To Be Determined

   |_Relationship city.hasPart:
     -  city.Neighborhood cuds object named <Industrie Gebiet>:
        uid: c694dffc-3e76-4b11-a752-52eee0ac7d11
        coordinates: [0 0]
- Cuds object named <Freiburg>:
  uid: 189eebe0-ead3-4d4d-a738-d25d13b976d5
  type: city.City
  superclasses: city.City, city.GeographicalPlace, city.PopulatedPlace, cuba.Entity
  values: coordinates: [1 0]
  description: 
    To Be Determined

   |_Relationship city.hasPart:
     -  city.Neighborhood cuds object named <Industrie Gebiet>:
        uid: c694dffc-3e76-4b11-a752-52eee0ac7d11
        coordinates: [1 0]

```

The coordinates attribute is changed also for the contained city.Neighborhood individual. I am pretty sure that's a bug. 
This is not the case for example in:

```
person = city.Citizen(name="Thomas")
child = city.Citizen(name = 'Tom')

person.add(child)

pretty_print(person)

person.age = 10

pretty_print(person)
```

Output: 

```
- Cuds object named <Thomas>:
  uid: b638e02e-a0e2-4607-9bd4-e5ea2e4ca113
  type: city.Citizen
  superclasses: city.Citizen, city.LivingBeing, city.Person, cuba.Entity
  values: age: 25
  description: 
    To Be Determined

   |_Relationship city.hasPart:
     -  city.Citizen cuds object named <Tom>:
        uid: d06f4c0d-0979-433f-ae1c-a644c4c10fe2
        age: 25
- Cuds object named <Thomas>:
  uid: b638e02e-a0e2-4607-9bd4-e5ea2e4ca113
  type: city.Citizen
  superclasses: city.Citizen, city.LivingBeing, city.Person, cuba.Entity
  values: age: 10
  description: 
    To Be Determined

   |_Relationship city.hasPart:
     -  city.Citizen cuds object named <Tom>:
        uid: d06f4c0d-0979-433f-ae1c-a644c4c10fe2
        age: 25
```
