### ISSUE TITLE
Add Black code formatting as a pre-commit

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#719]
We can make sure our code is always properly formatted by using [`pre-commits`](https://pre-commit.com/) paired with [`black`](https://black.readthedocs.io/en/stable/). Here is [a good guide](https://www.mattlayman.com/blog/2018/python-code-black/) on how to do it.

This way formatting would be done automatically for the developers with `pre-commit` installed.

**Comment by pablo-de-andres** [comment]
It can also be [easily added to GitHub actions](https://black.readthedocs.io/en/stable/integrations/github_actions.html).

**Comment by kysrpex** [comment]
After a quick overview, this seems nice. This addresses the styling aspects not covered by flake8. We should check though if flake8 can also do this task (reformat for you) or not at this fine-grained level.

**Comment by kysrpex** [comment]
After a quick overview, this seems nice. This addresses the styling aspects not covered by flake8. We should check though if flake8 can also do this task (reformat for you) or not at this fine-grained level.

> After a quick overview, this seems nice. This addresses the styling aspects not covered by flake8. We should check though if flake8 can also do this task (reformat for you) or not at this fine-grained level.

Ok, flake8 can notify you but [not automatically reformat code](https://stackoverflow.com/questions/54836680/how-to-make-pylint-flake8-or-pycodestyle-to-automatically-correct-errors).

**Comment by pablo-de-andres** [comment]
This is a configuration file we use in other projects, might be helpful as an initial idea:
```yml
---
repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: pretty-format-json
            args:
            - --autofix
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/psf/black
      rev: 22.1.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]

```
